# {"0":"calendar",
#   "1":"businessDayConvention",
#   "2":"endOfMonthConvention",
#   "3":"statusDate",
#   "4":"contractRole",
#   "5":"creatorID",
#   "6":"marketObjectCode",
#   "7":"counterpartyID",
#   "8":"contractPerformance",
#   "9":"seniority",
#   "10":"nonPerformingDate",
#   "11":"prepaymentPeriod",
#   "12":"gracePeriod",
#   "13":"delinquencyPeriod",
#   "14":"delinquencyRate",
#   "15":"cycleAnchorDateOfFee",
#   "16":"cycleOfFee",
#   "17":"feeBasis",
#   "18":"feeRate",
#   "19":"feeAccrued",
#   "20":"cycleAnchorDateOfInterestPayment",
#   "21":"cycleOfInterestPayment",
#   "22":"accruedInterest",
#   "23":"capitalizationEndDate",
#   "24":"cyclePointOfInterestPayment",
#   "25":"contractDealDate",
#   "26":"premiumDiscountAtIED",
#   "27":"purchaseDate",
#   "28":"priceAtPurchaseDate",
#   "29":"terminationDate",
#   "30":"priceAtTerminationDate",
#   "31":"creditLineAmount",
#   "32":"marketObjectCodeOfScalingIndex",
#   "33":"scalingIndexAtStatusDate",
#   "34":"cycleAnchorDateOfScalingIndex",
#   "35":"cycleOfScalingIndex",
#   "36":"scalingEffect",
#   "37":"marketValueObserved",
#   "38":"optionExerciseEndDate",
#   "39":"cycleAnchorDateOfOptionality",
#   "40":"cycleOfOptionality",
#   "41":"penaltyType",
#   "42":"penaltyRate",
#   "43":"prepaymentEffect",
#   "44":"cycleAnchorDateOfRateReset",
#   "45":"cycleOfRateReset",
#   "46":"rateSpread",
#   "47":"marketObjectCodeRateReset",
#   "48":"lifeCap",
#   "49":"lifeFloor",
#   "50":"periodCap",
#   "51":"periodFloor",
#   "52":"cyclePointOfRateReset",
#   "53":"fixingDays",
#   "54":"nextResetRate",
#   "55":"rateMultiplier",
#   "contractType":"PAM",
#   "contractID":112,
#   "nominalInterestRate":0.02,
#   "dayCountConvention":"30E/360",
#   "currency":"USD",
#   "initialExchangeDate":"2015-01-02T00:00:00",
#   "maturityDate":"2025-01-02T00:00:00",
#   "notionalPrincipal":1000,
#   "statusDate":"2015-01-01T00:00:00",
#   "contractRole":"RPA",
#   "cycleAnchorDateOfInterestPayment":"2016-01-02T00:00:00",
#   "cycleOfInterestPayment":"1Y+",
#   "contractDealDate":"2015-01-01T00:00:00",
#   "premiumDiscountAtIED":0,
#   "cycleOfRateReset":"2Y+",
#   "rateSpread":0.02,
#   "marketObjectCodeRateReset":"YC.USA.TREASURY"}


# pam <- Pam() 
# set(pam, what=list(
#   ContractID = "001",
#   Currency = "CHF",
#   Calendar = "MondayToFriday",
#   ContractRole = "RPA",                   # Real Position Asset
#   StatusDate       = "2012-12-31T00",     # on this day we analyse our PAM.
#   ContractDealDate = "2012-12-31T00",
#   InitialExchangeDate = "2013-01-01T00",  # here start the contract work
#   MaturityDate = "2013-03-31T00",         # the day of the repayment
#   NotionalPrincipal = 1000,               # nominal value
#   NominalInterestRate = 0.00,             # nominal Interest rate
#   PremiumDiscountAtIED = -100,
#   DayCountConvention = "30E/360",
#   BusinessDayConvention = "SCF",
#   MarketObjectCodeRateReset = "YC.USA.TREASURY"))




